name: Neo Wallet CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm install
        working-directory: frontend

      - name: Run Tests
        run: npm test
        working-directory: frontend

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
    
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v14
        with:
            aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            application_name: your-app-name
            environment_name: your-env-name
            version_label: ${{ github.run_id }}
            region: us-west-1  # or your AWS region
            zip_file: path-to-your-zipped-backend-code.zip

      - name: Build frontend
        run: |
            cd frontend
            npm run build

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
            args: --acl public-read --follow-symlinks --delete
            sync_dir: frontend/build/
            bucket_name: your-s3-bucket-name
            aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
